# Generated by Django 5.2.11 on 2026-02-07 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_method', models.CharField(choices=[('qr_scan', 'QR Scan'), ('manual', 'Manual'), ('self', 'Self Check-in')], default='qr_scan', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_guests', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_history', to='guests.guest')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'ordering': ['-created_at'],
            },
        ),
    ]
