# Generated by Django 5.2.11 on 2026-02-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('organizer', 'Event Organizer')], default='customer', help_text='Customer can purchase tickets, Organizer can create events', max_length=20),
        ),
    ]
