# Generated by Django 5.2.11 on 2026-02-07 18:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateTimeField()),
                ('event_end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=500)),
                ('venue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='event_banners/')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of guests allowed', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('allow_plus_one', models.BooleanField(default=False, help_text='Allow guests to bring a plus one')),
                ('require_rsvp', models.BooleanField(default=True, help_text='Require guests to RSVP before attending')),
                ('enable_self_checkin', models.BooleanField(default=False, help_text='Allow guests to check themselves in')),
                ('checkin_start_time', models.DateTimeField(blank=True, help_text='When check-in should start', null=True)),
                ('checkin_end_time', models.DateTimeField(blank=True, help_text='When check-in should end', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Make event publicly visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['-event_date'],
                'indexes': [models.Index(fields=['-event_date'], name='events_even_event_d_b32ef4_idx'), models.Index(fields=['organizer', '-created_at'], name='events_even_organiz_b0e8a9_idx'), models.Index(fields=['status'], name='events_even_status_5709b6_idx')],
            },
        ),
    ]
