# Generated by Django
from django.db import migrations, models
import uuid

def generate_slug_and_uuid(apps, schema_editor):
    """Generate unique slug and UUID for existing events"""
    from django.utils.text import slugify
    Event = apps.get_model('events', 'Event')
    for event in Event.objects.all():
        # Generate slug
        base_slug = slugify(event.title)
        slug = base_slug
        counter = 1
        # Ensure slug is unique
        while Event.objects.filter(slug=slug).exclude(pk=event.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        event.slug = slug
        event.unique_id = uuid.uuid4()
        event.save()

class Migration(migrations.Migration):
    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        # Step 1: Add fields without unique constraint
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=300, null=True, blank=True, db_index=False),
        ),
        migrations.AddField(
            model_name='event',
            name='unique_id',
            field=models.UUIDField(null=True, blank=True, editable=False, db_index=False),
        ),
        # Step 2: Populate existing records
        migrations.RunPython(generate_slug_and_uuid, migrations.RunPython.noop),
        # Step 3: Add unique constraint using RunSQL to avoid auto-index creation
        migrations.RunSQL(
            sql=[
                'ALTER TABLE events_event ALTER COLUMN slug SET NOT NULL;',
                'ALTER TABLE events_event ADD CONSTRAINT events_event_slug_key UNIQUE (slug);',
                'ALTER TABLE events_event ALTER COLUMN unique_id SET NOT NULL;',
                'ALTER TABLE events_event ADD CONSTRAINT events_event_unique_id_key UNIQUE (unique_id);',
            ],
            reverse_sql=[
                'ALTER TABLE events_event DROP CONSTRAINT IF EXISTS events_event_slug_key;',
                'ALTER TABLE events_event ALTER COLUMN slug DROP NOT NULL;',
                'ALTER TABLE events_event DROP CONSTRAINT IF EXISTS events_event_unique_id_key;',
                'ALTER TABLE events_event ALTER COLUMN unique_id DROP NOT NULL;',
            ],
        ),
        # Step 4: Add additional indexes
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='events_even_slug_30eb0f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['unique_id'], name='events_even_unique__e628af_idx'),
        ),
    ]