# Generated by Django 5.2.11 on 2026-02-07 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the guest', null=True)),
                ('plus_one_allowed', models.BooleanField(default=False)),
                ('plus_one_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('attended', 'Attended'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('rsvp_status', models.BooleanField(default=False, help_text="Has the guest RSVP'd?")),
                ('rsvp_date', models.DateTimeField(blank=True, null=True)),
                ('has_checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.CharField(blank=True, help_text='Staff member who checked in the guest', max_length=255, null=True)),
                ('invitation_sent', models.BooleanField(default=False)),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event')),
            ],
            options={
                'verbose_name': 'guest',
                'verbose_name_plural': 'guests',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['event', 'email'], name='guests_gues_event_i_03239c_idx'), models.Index(fields=['event', 'status'], name='guests_gues_event_i_80021b_idx'), models.Index(fields=['has_checked_in'], name='guests_gues_has_che_19192a_idx')],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
